---
version: 2
multi-ecosystem-groups:
  infra:
    schedule:
      interval: "weekly"

updates:

  - package-ecosystem: "docker"
    directory: "/"
    multi-ecosystem-group: "infra"
    patterns:
      - "nginx"
      - "redis"
      - "postgres"
    ignore: 
      - dependency-name: "amdocs/platform/amaiz-framework-sdk"

  - package-ecosystem: "helm"
    directory: "/"
    multi-ecosystem-group: "infra"
    patterns:
      - "*"
