---
version: 2
multi-ecosystem-groups:
  infra:
    schedule:
      interval: "weekly"

updates:

  - package-ecosystem: "docker"
    directory: "/"
    patterns: ["nginx", "redis", "postgres"]
    multi-ecosystem-group: "infra"

  - package-ecosystem: "helm"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "infra"
