---
version: 2
multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"
      
updates:

  - package-ecosystem: "helm"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "infrastructure"
  - package-ecosystem: "docker"
    directory: "/"
    patterns: ["nginx", "redis", "postgres"]
    multi-ecosystem-group: "infrastructure"
    ignore: 
      - dependency-name: "amdocs/platform/amaiz-framework-sdk"
